declare
	CNT INTEGER:=0;
begin
	SELECT COUNT(*) INTO CNT
		FROM USER_CONSTRAINTS
			WHERE CONSTRAINT_NAME = UPPER('%CONSTRAINT_NAME%') and TABLE_NAME = UPPER('%TABLE_NAME%') and CONSTRAINT_TYPE = 'R';
	IF(CNT=0) THEN
		EXECUTE IMMEDIATE 'ALTER TABLE %TABLE_NAME% ADD CONSTRAINT %CONSTRAINT_NAME%
							CHECK (%CHK_CONDITION%)';
		DBMS_OUTPUT.PUT_LINE('Ограничение %CONSTRAINT_NAME% создано');
	else
		DBMS_OUTPUT.PUT_LINE('Ограничение %CONSTRAINT_NAME% уже существует');
	end if;
end;
/
SHOW ERRORS